name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "20 0 1 * *"

jobs:
  build:
    name: Sync Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check if doc2en submodule is updated
        id: submodules-en
        run: |
          git diff --quiet HEAD -- ./doc2en
          echo "::set-output name=has_changes::$?"
      - name: Check if doc2zh submodule is updated
        id: submodules-zh
        run: |
          git diff --quiet HEAD -- ./doc2zh
          echo "::set-output name=has_changes::$?"
      - name: Update
        if: steps.submodules-en.outputs.has_changes == '1' || steps.submodules-zh.outputs.has_changes == '1'
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "feat: Update submodules"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
